cursor #e4e2e3
cursor_text_color #c6c6cd

foreground            #e4e2e3
background            #131315
selection_foreground  #2d3038
selection_background  #c4c6d0
url_color             #bec6de

color0   #131315
color1   #ff7298
color2   #6fde80
color3   #fff872
color4   #aeb7d2
color5   #4b5266
color6   #bec6de
color7   #dbdee9
color8   #858890
color9   #ff9fb9
color10  #a5ffb3
color11  #fffba5
color12  #d6ddf4
color13  #e5ebff
color14  #eef2ff
color15  #f8faff
